# iBold/BOLD Systems sequence data ingestion script

See https://www.boldsystems.org/index.php/Public_BINSearch?query=Australia for details on data
See https://v3.boldsystems.org/index.php/resources/api?type=webservices#combined for API docs

In [115]:
import pandas as pd
import pandas_read_xml as pdx
from pandas_read_xml import flatten, fully_flatten, auto_separate_tables

df = pdx.read_xml('http://v3.boldsystems.org/index.php/API_Public/combined?format=xml&geo=Australia', ['bold_records'])

# df = pd.read_xml("http://v3.boldsystems.org/index.php/API_Public/combined?format=xml&geo=Australia&taxon=Reptilia", dtype={'specimen_identifiers': object}) 
# df = pd.read_table("../data/bold_data.tsv", dtype='object', parse_dates=['collectiondate']) 
# columns:
# processid	sampleid	recordID	catalognum	fieldnum	institution_storing	bin_uri	phylum_taxID	phylum_name	
# class_taxID	class_name	order_taxID	order_name	family_taxID	family_name	subfamily_taxID	subfamily_name	
# genus_taxID	genus_name	species_taxID	species_name	subspecies_taxID	subspecies_name	identification_provided_by	
# voucher_type	tissue_type	collectors	collectiondate	lifestage	sex	reproduction	extrainfo	notes	lat	lon	
# coord_source	coord_accuracy	country	province	region	exactsite
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   @xsi:noNamespaceSchemaLocation  1 non-null      object
 1   @xmlns:xsi                      1 non-null      object
 2   record                          1 non-null      object
dtypes: object(3)
memory usage: 152.0+ bytes

,@xsi:noNamespaceSchemaLocation,@xmlns:xsi,record
0,http://v3.boldsystems.org/schemas/BOLDPublic_r...,http://www.w3.org/2001/XMLSchema-instance,"[{'record_id': '967799', 'processid': 'BENT040..."

In [116]:
df = df.pipe(flatten)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 3 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   @xsi:noNamespaceSchemaLocation  388 non-null    object
 1   @xmlns:xsi                      388 non-null    object
 2   record                          388 non-null    object
dtypes: object(3)
memory usage: 9.2+ KB

In [117]:
# df = df.pipe(flatten)
df = df.drop('@xsi:noNamespaceSchemaLocation', axis=1)
df = df.drop('@xmlns:xsi', axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   record  388 non-null    object
dtypes: object(1)
memory usage: 3.2+ KB

In [118]:
df = df.pipe(fully_flatten)
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 55 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   record|bin_uri                                      695 non-null    object
 1   record|collection_event|collectiondate              635 non-null    object
 2   record|collection_event|collectors                  472 non-null    object
 3   record|collection_event|coordinates|coord_accuracy  2 non-null      object
 4   record|collection_event|coordinates|coord_source    6 non-null      object
 5   record|collection_event|coordinates|lat             642 non-null    object
 6   record|collection_event|coordinates|lon             642 non-null    object
 7   record|collection_event|country                     701 non-null    object
 8   record|collection_event|exactsite                   164 non-null    object
 9   record|collection_event|province                    696 non-null    object
 10  record|collection_event|region                      34 non-null     object
 11  record|notes                                        19 non-null     object
 12  record|processid                                    701 non-null    object
 13  record|record_id                                    701 non-null    object
 14  record|sequences|sequence|genbank_accession         192 non-null    object
 15  record|sequences|sequence|markercode                699 non-null    object
 16  record|sequences|sequence|nucleotides               699 non-null    object
 17  record|sequences|sequence|sequenceID                699 non-null    object
 18  record|specimen_details|extrainfo                   57 non-null     object
 19  record|specimen_details|lifestage                   139 non-null    object
 20  record|specimen_details|reproduction                518 non-null    object
 21  record|specimen_details|sex                         146 non-null    object
 22  record|specimen_details|voucher_desc                0 non-null      object
 23  record|specimen_details|voucher_type                166 non-null    object
 24  record|specimen_identifiers|catalognum              652 non-null    object
 25  record|specimen_identifiers|fieldnum                323 non-null    object
 26  record|specimen_identifiers|institution_storing     701 non-null    object
 27  record|specimen_identifiers|sampleid                701 non-null    object
 28  record|specimen_imagery|media|caption               0 non-null      object
 29  record|specimen_imagery|media|copyright             6 non-null      object
 30  record|specimen_imagery|media|image_file            6 non-null      object
 31  record|specimen_imagery|media|mediaID               6 non-null      object
 32  record|specimen_imagery|media|metatags              0 non-null      object
 33  record|taxonomy|class|taxon|name                    701 non-null    object
 34  record|taxonomy|class|taxon|taxID                   701 non-null    object
 35  record|taxonomy|family|taxon|name                   230 non-null    object
 36  record|taxonomy|family|taxon|taxID                  230 non-null    object
 37  record|taxonomy|genus|taxon|name                    229 non-null    object
 38  record|taxonomy|genus|taxon|taxID                   229 non-null    object
 39  record|taxonomy|identification_provided_by          470 non-null    object
 40  record|taxonomy|order|taxon|name                    701 non-null    object
 41  record|taxonomy|order|taxon|taxID                   701 non-null    object
 42  record|taxonomy|phylum|taxon|name                   701 non-null    object
 43  record|taxonomy|phylum|taxon|taxID                  701 non-null    object
 44  record|taxonomy|species|taxon|name                  229 non-null    object
 45  record|taxonomy|species|taxon|taxID                 229 non-null    object
 46  record|taxonomy|subfamily|taxon|name                186 non-null    object
 47  record|taxonomy|subfamily|taxon|taxID               186 non-null    object
 48  record|tracefiles|read|direction                    640 non-null    object
 49  record|tracefiles|read|markercode                   640 non-null    object
 50  record|tracefiles|read|read_id                      640 non-null    object
 51  record|tracefiles|read|run_date                     640 non-null    object
 52  record|tracefiles|read|seq_primer                   640 non-null    object
 53  record|tracefiles|read|sequencing_center            640 non-null    object
 54  record|tracefiles|read|trace_link                   640 non-null    object
dtypes: object(55)
memory usage: 301.3+ KB

,record|bin_uri,record|collection_event|collectiondate,record|collection_event|collectors,record|collection_event|coordinates|coord_accuracy,record|collection_event|coordinates|coord_source,record|collection_event|coordinates|lat,record|collection_event|coordinates|lon,record|collection_event|country,record|collection_event|exactsite,record|collection_event|province,...,record|taxonomy|species|taxon|taxID,record|taxonomy|subfamily|taxon|name,record|taxonomy|subfamily|taxon|taxID,record|tracefiles|read|direction,record|tracefiles|read|markercode,record|tracefiles|read|read_id,record|tracefiles|read|run_date,record|tracefiles|read|seq_primer,record|tracefiles|read|sequencing_center,record|tracefiles|read|trace_link
0,BOLD:ACF0415,2010-10-17,P.Hebert,None,GPS,-35.6528,150.146,Australia,Kings Hwy 52,New South Wales,...,515104,Hydrophiinae,473453,F,COI-5P,5001846,2013-04-30T08:55:39,M13F,Biodiversity Institute of Ontario,http://trace.boldsystems.org/traceIO/bold.org/...
1,BOLD:ACF0415,2010-10-17,P.Hebert,None,GPS,-35.6528,150.146,Australia,Kings Hwy 52,New South Wales,...,515104,Hydrophiinae,473453,R,COI-5P,5001867,2013-04-30T08:55:39,M13R,Biodiversity Institute of Ontario,http://trace.boldsystems.org/traceIO/bold.org/...
2,BOLD:ACE9617,2010-10-17,P.Hebert,None,GPS,-35.4374,149.799,Australia,Kings Hwy 52,New South Wales,...,171558,Chelodininae,757233,F,COI-5P,5001848,2013-04-30T08:55:39,M13F,Biodiversity Institute of Ontario,http://trace.boldsystems.org/traceIO/bold.org/...
3,BOLD:ACE9617,2010-10-17,P.Hebert,None,GPS,-35.4374,149.799,Australia,Kings Hwy 52,New South Wales,...,171558,Chelodininae,757233,R,COI-5P,5001869,2013-04-30T08:55:39,M13R,Biodiversity Institute of Ontario,http://trace.boldsystems.org/traceIO/bold.org/...
4,BOLD:ADI2959,2002-10-07,None,None,None,-15.6469,145.22,Australia,"Cooktown, ca. 20 km (by road) S of, Black Moun...",Queensland,...,783178,Eugongylinae,757230,f,COI-5P,10282446,2014-03-28T10:23:01,REPTBCf,"Smithsonian Institution, Laboratories of Analy...",http://trace.boldsystems.org/traceIO/bold.org/...

In [119]:
# Cleanup field names and map to DwC where possible
field_mapping = {
    # DwC fields
    'record|collection_event|collectiondate': 'eventDate',
    'record|collection_event|collectors': 'recordedBy',
    'record|collection_event|coordinates|coord_accuracy':'coordinatePrecision',
    'record|collection_event|coordinates|coord_source':'georeferenceSources',
    'record|collection_event|coordinates|lat':'decimalLatitude',
    'record|collection_event|coordinates|lon':'decimalLongitude',
    'record|collection_event|country':'country',
    'record|collection_event|exactsite':'locationRemarks',
    'record|collection_event|province':'stateProvince',
    'record|collection_event|region':'locality',
    'record|notes':'fieldNotes', # eventRemarks
    'record|processid':'recordNumber',
    'record|record_id':'occurrenceID',
    'record|bin_uri':'bold_bin_uri',
    # use df.apply to merge following fields into associatedSequences
    # 'record|sequences|sequence|genbank_accession':'ncbi_accession',
    # 'record|sequences|sequence|sequenceID':'',
    # 'record|sequences|sequence|nucleotides':'',
    'record|specimen_details|extrainfo':'identificationRemarks',
    'record|specimen_details|lifestage':'lifeStage',
    'record|specimen_details|reproduction':'bold_reproduction',
    'record|specimen_details|sex':'sex',
    'record|specimen_details|voucher_desc':'dispositionProperty',
    'record|specimen_details|voucher_type':'bold_voucher_type',
    'record|specimen_identifiers|catalognum':'otherCatalogNumbers',
    'record|specimen_identifiers|fieldnum':'fieldNumber',
    'record|specimen_identifiers|institution_storing':'ownerInstitutionCode',
    'record|specimen_identifiers|sampleid':'materialSampleID',
    # use df.apply to merge following fields into associatedMedia 
    # specimen_imagery|media|caption 
    # specimen_imagery|media|copyright  
    # specimen_imagery|media|image_file         
    # specimen_imagery|media|mediaID
    # specimen_imagery|media|metatags
    'record|taxonomy|identification_provided_by':'identifiedBy',
    'record|taxonomy|class|taxon|name':'class',
    'record|taxonomy|class|taxon|taxID':'classID',
    'record|taxonomy|family|taxon|name':'family',
    'record|taxonomy|family|taxon|taxID':'familyID',
    'record|taxonomy|genus|taxon|name':'genus',
    'record|taxonomy|genus|taxon|taxID':'genusID',
    'record|taxonomy|order|taxon|name':'order',
    'record|taxonomy|order|taxon|taxID':'orderID',
    'record|taxonomy|phylum|taxon|name':'phylum',
    'record|taxonomy|phylum|taxon|taxID':'phylumID',
    'record|taxonomy|species|taxon|name':'species',
    'record|taxonomy|species|taxon|taxID':'speciesID',
    # use df.apply to merge following fields into associatedMedia 
    # record|tracefiles|read|*
}

# keep copies of DwC matched columns (just in case)
df['scientificName'] = df['record|taxonomy|species|taxon|name'] 

# do rename
df.rename(
  columns = field_mapping, 
  inplace = True
)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 56 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   bold_bin_uri                                 695 non-null    object
 1   eventDate                                    635 non-null    object
 2   recordedBy                                   472 non-null    object
 3   coordinatePrecision                          2 non-null      object
 4   georeferenceSources                          6 non-null      object
 5   decimalLatitude                              642 non-null    object
 6   decimalLongitude                             642 non-null    object
 7   country                                      701 non-null    object
 8   locationRemarks                              164 non-null    object
 9   stateProvince                                696 non-null    object
 10  locality                                     34 non-null     object
 11  fieldNotes                                   19 non-null     object
 12  recordNumber                                 701 non-null    object
 13  occurrenceID                                 701 non-null    object
 14  record|sequences|sequence|genbank_accession  192 non-null    object
 15  record|sequences|sequence|markercode         699 non-null    object
 16  record|sequences|sequence|nucleotides        699 non-null    object
 17  record|sequences|sequence|sequenceID         699 non-null    object
 18  identificationRemarks                        57 non-null     object
 19  lifeStage                                    139 non-null    object
 20  bold_reproduction                            518 non-null    object
 21  sex                                          146 non-null    object
 22  dispositionProperty                          0 non-null      object
 23  bold_voucher_type                            166 non-null    object
 24  otherCatalogNumbers                          652 non-null    object
 25  fieldNumber                                  323 non-null    object
 26  ownerInstitutionCode                         701 non-null    object
 27  materialSampleID                             701 non-null    object
 28  record|specimen_imagery|media|caption        0 non-null      object
 29  record|specimen_imagery|media|copyright      6 non-null      object
 30  record|specimen_imagery|media|image_file     6 non-null      object
 31  record|specimen_imagery|media|mediaID        6 non-null      object
 32  record|specimen_imagery|media|metatags       0 non-null      object
 33  class                                        701 non-null    object
 34  classID                                      701 non-null    object
 35  family                                       230 non-null    object
 36  familyID                                     230 non-null    object
 37  genus                                        229 non-null    object
 38  genusID                                      229 non-null    object
 39  identifiedBy                                 470 non-null    object
 40  order                                        701 non-null    object
 41  orderID                                      701 non-null    object
 42  phylum                                       701 non-null    object
 43  phylumID                                     701 non-null    object
 44  species                                      229 non-null    object
 45  speciesID                                    229 non-null    object
 46  record|taxonomy|subfamily|taxon|name         186 non-null    object
 47  record|taxonomy|subfamily|taxon|taxID        186 non-null    object
 48  record|tracefiles|read|direction             640 non-null    object
 49  record|tracefiles|read|markercode            640 non-null    object
 50  record|tracefiles|read|read_id               640 non-null    object
 51  record|tracefiles|read|run_date              640 non-null    object
 52  record|tracefiles|read|seq_primer            640 non-null    object
 53  record|tracefiles|read|sequencing_center     640 non-null    object
 54  record|tracefiles|read|trace_link            640 non-null    object
 55  scientificName                               229 non-null    object
dtypes: object(56)
memory usage: 306.8+ KB

,bold_bin_uri,eventDate,recordedBy,coordinatePrecision,georeferenceSources,decimalLatitude,decimalLongitude,country,locationRemarks,stateProvince,...,record|taxonomy|subfamily|taxon|name,record|taxonomy|subfamily|taxon|taxID,record|tracefiles|read|direction,record|tracefiles|read|markercode,record|tracefiles|read|read_id,record|tracefiles|read|run_date,record|tracefiles|read|seq_primer,record|tracefiles|read|sequencing_center,record|tracefiles|read|trace_link,scientificName
0,BOLD:ACF0415,2010-10-17,P.Hebert,None,GPS,-35.6528,150.146,Australia,Kings Hwy 52,New South Wales,...,Hydrophiinae,473453,F,COI-5P,5001846,2013-04-30T08:55:39,M13F,Biodiversity Institute of Ontario,http://trace.boldsystems.org/traceIO/bold.org/...,Pseudechis porphyriacus
1,BOLD:ACF0415,2010-10-17,P.Hebert,None,GPS,-35.6528,150.146,Australia,Kings Hwy 52,New South Wales,...,Hydrophiinae,473453,R,COI-5P,5001867,2013-04-30T08:55:39,M13R,Biodiversity Institute of Ontario,http://trace.boldsystems.org/traceIO/bold.org/...,Pseudechis porphyriacus
2,BOLD:ACE9617,2010-10-17,P.Hebert,None,GPS,-35.4374,149.799,Australia,Kings Hwy 52,New South Wales,...,Chelodininae,757233,F,COI-5P,5001848,2013-04-30T08:55:39,M13F,Biodiversity Institute of Ontario,http://trace.boldsystems.org/traceIO/bold.org/...,Chelodina longicollis
3,BOLD:ACE9617,2010-10-17,P.Hebert,None,GPS,-35.4374,149.799,Australia,Kings Hwy 52,New South Wales,...,Chelodininae,757233,R,COI-5P,5001869,2013-04-30T08:55:39,M13R,Biodiversity Institute of Ontario,http://trace.boldsystems.org/traceIO/bold.org/...,Chelodina longicollis
4,BOLD:ADI2959,2002-10-07,None,None,None,-15.6469,145.22,Australia,"Cooktown, ca. 20 km (by road) S of, Black Moun...",Queensland,...,Eugongylinae,757230,f,COI-5P,10282446,2014-03-28T10:23:01,REPTBCf,"Smithsonian Institution, Laboratories of Analy...",http://trace.boldsystems.org/traceIO/bold.org/...,Liburnascincus scirtetis

In [120]:
# process sequences data
sequenceFields = {
  'sequenceID': 'record|sequences|sequence|sequenceID',
  'genbank_accession': 'record|sequences|sequence|genbank_accession',
  'markercode': 'record|sequences|sequence|markercode',
  'nucleotides': 'record|sequences|sequence|nucleotides',
}

def addAssociatedeSequenceData(row):
  sequenceData = {}
  for sd in sequenceFields:
    sequenceData[sd] = row[sequenceFields[sd]]
  return [sequenceData]

df['associatedSequences'] = df.apply(addAssociatedeSequenceData, axis=1)
df.drop(sequenceFields.values(), axis=1, inplace=True)

# process images data
imagesFields = {
  'mediaID': 'record|specimen_imagery|media|mediaID',
  'image_file': 'record|specimen_imagery|media|image_file',
  'metatags': 'record|specimen_imagery|media|metatags',
  'copyright': 'record|specimen_imagery|media|copyright',
  'caption': 'record|specimen_imagery|media|caption',
}

def associatedImageData(row):
  imageData = {}
  for id in imagesFields:
    imageData[id] = row[imagesFields[id]]
  return [imageData]

df['associatedMedia'] = df.apply(associatedImageData, axis=1)
df.drop(imagesFields.values(), axis=1, inplace=True)

# process traces data
tracesFields = {
  'direction': 'record|tracefiles|read|direction',
  'read_id': 'record|tracefiles|read|read_id',
  'markercode': 'record|tracefiles|read|markercode',
  'run_date': 'record|tracefiles|read|run_date',
  'seq_primer': 'record|tracefiles|read|seq_primer',
  'sequencing_center': 'record|tracefiles|read|sequencing_center',
  'trace_link': 'record|tracefiles|read|trace_link',
}

def addTracesData(row):
  tdata = {}
  for tf in tracesFields:
    tdata[tf] = row[tracesFields[tf]]
  return [tdata]

df['bold_tracefiles_read'] = df.apply(addTracesData, axis=1)
df.drop(tracesFields.values(), axis=1, inplace=True)
  
df.drop(['record|taxonomy|subfamily|taxon|name','record|taxonomy|subfamily|taxon|taxID'], axis=1, inplace=True)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   bold_bin_uri           695 non-null    object
 1   eventDate              635 non-null    object
 2   recordedBy             472 non-null    object
 3   coordinatePrecision    2 non-null      object
 4   georeferenceSources    6 non-null      object
 5   decimalLatitude        642 non-null    object
 6   decimalLongitude       642 non-null    object
 7   country                701 non-null    object
 8   locationRemarks        164 non-null    object
 9   stateProvince          696 non-null    object
 10  locality               34 non-null     object
 11  fieldNotes             19 non-null     object
 12  recordNumber           701 non-null    object
 13  occurrenceID           701 non-null    object
 14  identificationRemarks  57 non-null     object
 15  lifeStage              139 non-null    object
 16  bold_reproduction      518 non-null    object
 17  sex                    146 non-null    object
 18  dispositionProperty    0 non-null      object
 19  bold_voucher_type      166 non-null    object
 20  otherCatalogNumbers    652 non-null    object
 21  fieldNumber            323 non-null    object
 22  ownerInstitutionCode   701 non-null    object
 23  materialSampleID       701 non-null    object
 24  class                  701 non-null    object
 25  classID                701 non-null    object
 26  family                 230 non-null    object
 27  familyID               230 non-null    object
 28  genus                  229 non-null    object
 29  genusID                229 non-null    object
 30  identifiedBy           470 non-null    object
 31  order                  701 non-null    object
 32  orderID                701 non-null    object
 33  phylum                 701 non-null    object
 34  phylumID               701 non-null    object
 35  species                229 non-null    object
 36  speciesID              229 non-null    object
 37  scientificName         229 non-null    object
 38  associatedSequences    701 non-null    object
 39  associatedMedia        701 non-null    object
 40  bold_tracefiles_read   701 non-null    object
dtypes: object(41)
memory usage: 224.7+ KB

,bold_bin_uri,eventDate,recordedBy,coordinatePrecision,georeferenceSources,decimalLatitude,decimalLongitude,country,locationRemarks,stateProvince,...,order,orderID,phylum,phylumID,species,speciesID,scientificName,associatedSequences,associatedMedia,bold_tracefiles_read
0,BOLD:ACF0415,2010-10-17,P.Hebert,None,GPS,-35.6528,150.146,Australia,Kings Hwy 52,New South Wales,...,Squamata,367,Chordata,18,Pseudechis porphyriacus,515104,Pseudechis porphyriacus,"[{'sequenceID': '5161496', 'genbank_accession'...","[{'mediaID': '1902893', 'image_file': 'http://...","[{'direction': 'F', 'read_id': '5001846', 'mar..."
1,BOLD:ACF0415,2010-10-17,P.Hebert,None,GPS,-35.6528,150.146,Australia,Kings Hwy 52,New South Wales,...,Squamata,367,Chordata,18,Pseudechis porphyriacus,515104,Pseudechis porphyriacus,"[{'sequenceID': '5161496', 'genbank_accession'...","[{'mediaID': '1902893', 'image_file': 'http://...","[{'direction': 'R', 'read_id': '5001867', 'mar..."
2,BOLD:ACE9617,2010-10-17,P.Hebert,None,GPS,-35.4374,149.799,Australia,Kings Hwy 52,New South Wales,...,Testudines,384,Chordata,18,Chelodina longicollis,171558,Chelodina longicollis,"[{'sequenceID': '5161498', 'genbank_accession'...","[{'mediaID': '1902895', 'image_file': 'http://...","[{'direction': 'F', 'read_id': '5001848', 'mar..."
3,BOLD:ACE9617,2010-10-17,P.Hebert,None,GPS,-35.4374,149.799,Australia,Kings Hwy 52,New South Wales,...,Testudines,384,Chordata,18,Chelodina longicollis,171558,Chelodina longicollis,"[{'sequenceID': '5161498', 'genbank_accession'...","[{'mediaID': '1902895', 'image_file': 'http://...","[{'direction': 'R', 'read_id': '5001869', 'mar..."
4,BOLD:ADI2959,2002-10-07,None,None,None,-15.6469,145.22,Australia,"Cooktown, ca. 20 km (by road) S of, Black Moun...",Queensland,...,Squamata,367,Chordata,18,Liburnascincus scirtetis,783178,Liburnascincus scirtetis,"[{'sequenceID': '9474096', 'genbank_accession'...","[{'mediaID': nan, 'image_file': nan, 'metatags...","[{'direction': 'f', 'read_id': '10282446', 'ma..."

In [ ]:
# save to CSV file
df.to_csv(f"/data/arga-data/bold_australia_data.csv", index=False)